/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package_exercice2;

import javax.swing.ListModel;

/**
 *
 * @author FRS4440A
 */
public class Exercice2 extends javax.swing.JFrame {

    /**
     * Creates new form Exercice2
     */
    public Exercice2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        PanelFichier = new javax.swing.JPanel();
        BoutonParcourir = new javax.swing.JButton();
        LabelFichier = new javax.swing.JLabel();
        PanelNomFichier = new javax.swing.JScrollPane();
        TextAreaNomFichier = new javax.swing.JTextArea();
        PanelOptions = new javax.swing.JPanel();
        PanelOptionsGauche = new javax.swing.JPanel();
        SpinnerNombreCopies = new javax.swing.JSpinner();
        LabelNombreCopies = new javax.swing.JLabel();
        ComboBoxFormat = new javax.swing.JComboBox<>();
        LabelFormat = new javax.swing.JLabel();
        CheckBoxRectoVerso = new javax.swing.JCheckBox();
        PanelOptionDroit = new javax.swing.JPanel();
        RadioBoutonNoirBlanc = new javax.swing.JRadioButton();
        RadioBoutonCouleur = new javax.swing.JRadioButton();
        ComboBoxQualite = new javax.swing.JComboBox<>();
        LabelQualitéPapier = new javax.swing.JLabel();
        PanelPlanification = new javax.swing.JPanel();
        BoutonAjouter = new javax.swing.JButton();
        BoutonModifier = new javax.swing.JButton();
        BoutonSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListImpressionPlanifiees = new javax.swing.JList<>();
        PanelPrix = new javax.swing.JPanel();
        TestFieldPrix = new javax.swing.JTextField();

        FileChooser.setDialogTitle("Fichier à imprimer");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion impressions");
        setName("Gestion impressions"); // NOI18N

        PanelFichier.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fichier à imprimer"));

        BoutonParcourir.setText("Parcourir...");
        BoutonParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonParcourirActionPerformed(evt);
            }
        });

        LabelFichier.setText("Nom du fichier :");

        PanelNomFichier.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        PanelNomFichier.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        TextAreaNomFichier.setEditable(false);
        TextAreaNomFichier.setColumns(20);
        TextAreaNomFichier.setRows(5);
        TextAreaNomFichier.setAutoscrolls(false);
        TextAreaNomFichier.setEnabled(false);
        TextAreaNomFichier.setFocusable(false);
        PanelNomFichier.setViewportView(TextAreaNomFichier);

        javax.swing.GroupLayout PanelFichierLayout = new javax.swing.GroupLayout(PanelFichier);
        PanelFichier.setLayout(PanelFichierLayout);
        PanelFichierLayout.setHorizontalGroup(
            PanelFichierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFichierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelNomFichier, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoutonParcourir)
                .addContainerGap())
        );
        PanelFichierLayout.setVerticalGroup(
            PanelFichierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFichierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFichierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFichier)
                    .addComponent(BoutonParcourir))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(PanelFichierLayout.createSequentialGroup()
                .addComponent(PanelNomFichier, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Options d'impression"));

        PanelOptionsGauche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SpinnerNombreCopies.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinnerNombreCopiesStateChanged(evt);
            }
        });

        LabelNombreCopies.setText("Nb de copies");

        ComboBoxFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A3", "A4", "A5", "A6" }));
        ComboBoxFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFormatActionPerformed(evt);
            }
        });

        LabelFormat.setText("Format");

        CheckBoxRectoVerso.setText("Recto/Verso");
        CheckBoxRectoVerso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxRectoVersoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelOptionsGaucheLayout = new javax.swing.GroupLayout(PanelOptionsGauche);
        PanelOptionsGauche.setLayout(PanelOptionsGaucheLayout);
        PanelOptionsGaucheLayout.setHorizontalGroup(
            PanelOptionsGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsGaucheLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelOptionsGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxRectoVerso)
                    .addGroup(PanelOptionsGaucheLayout.createSequentialGroup()
                        .addGroup(PanelOptionsGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNombreCopies)
                            .addComponent(LabelFormat))
                        .addGap(18, 18, 18)
                        .addGroup(PanelOptionsGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SpinnerNombreCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        PanelOptionsGaucheLayout.setVerticalGroup(
            PanelOptionsGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsGaucheLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelOptionsGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombreCopies)
                    .addComponent(SpinnerNombreCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelOptionsGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFormat)
                    .addComponent(ComboBoxFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxRectoVerso)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PanelOptionDroit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        RadioBoutonNoirBlanc.setText("Noir et Blanc");
        RadioBoutonNoirBlanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBoutonNoirBlancActionPerformed(evt);
            }
        });

        RadioBoutonCouleur.setText("Couleur");
        RadioBoutonCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBoutonCouleurActionPerformed(evt);
            }
        });

        ComboBoxQualite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economique", "Couché", "Supérieure", "Texturé", "Recyclé", "Spéciaux" }));
        ComboBoxQualite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxQualiteActionPerformed(evt);
            }
        });

        LabelQualitéPapier.setText("Qualité du papier");

        javax.swing.GroupLayout PanelOptionDroitLayout = new javax.swing.GroupLayout(PanelOptionDroit);
        PanelOptionDroit.setLayout(PanelOptionDroitLayout);
        PanelOptionDroitLayout.setHorizontalGroup(
            PanelOptionDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionDroitLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelOptionDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioBoutonCouleur)
                    .addComponent(RadioBoutonNoirBlanc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOptionDroitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelQualitéPapier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComboBoxQualite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        PanelOptionDroitLayout.setVerticalGroup(
            PanelOptionDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionDroitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RadioBoutonNoirBlanc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioBoutonCouleur)
                .addGap(18, 18, 18)
                .addGroup(PanelOptionDroitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxQualite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelQualitéPapier, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelOptionsLayout = new javax.swing.GroupLayout(PanelOptions);
        PanelOptions.setLayout(PanelOptionsLayout);
        PanelOptionsLayout.setHorizontalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelOptionsGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelOptionDroit, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        PanelOptionsLayout.setVerticalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelOptionDroit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelOptionsGauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PanelPlanification.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Impressions planifiées"));

        BoutonAjouter.setText("Ajouter");
        BoutonAjouter.setEnabled(false);
        BoutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonAjouterActionPerformed(evt);
            }
        });

        BoutonModifier.setText("Modifier");
        BoutonModifier.setEnabled(false);

        BoutonSupprimer.setText("Supprimer");
        BoutonSupprimer.setEnabled(false);
        BoutonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSupprimerActionPerformed(evt);
            }
        });

        ListImpressionPlanifiees.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListImpressionPlanifiees.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListImpressionPlanifieesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListImpressionPlanifiees);

        javax.swing.GroupLayout PanelPlanificationLayout = new javax.swing.GroupLayout(PanelPlanification);
        PanelPlanification.setLayout(PanelPlanificationLayout);
        PanelPlanificationLayout.setHorizontalGroup(
            PanelPlanificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlanificationLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(BoutonAjouter)
                .addGap(18, 18, 18)
                .addComponent(BoutonModifier)
                .addGap(18, 18, 18)
                .addComponent(BoutonSupprimer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPlanificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        PanelPlanificationLayout.setVerticalGroup(
            PanelPlanificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPlanificationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPlanificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoutonAjouter)
                    .addComponent(BoutonModifier)
                    .addComponent(BoutonSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelPrix.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Prix des impressions planifiées"));

        TestFieldPrix.setEditable(false);
        TestFieldPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestFieldPrixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrixLayout = new javax.swing.GroupLayout(PanelPrix);
        PanelPrix.setLayout(PanelPrixLayout);
        PanelPrixLayout.setHorizontalGroup(
            PanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TestFieldPrix)
                .addContainerGap())
        );
        PanelPrixLayout.setVerticalGroup(
            PanelPrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrixLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TestFieldPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelPlanification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPrix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PanelFichier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPlanification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonParcourirActionPerformed
        // TODO add your handling code here:
        int resultat=FileChooser.showOpenDialog(this);
        if (resultat==0){
            TextAreaNomFichier.append(FileChooser.getSelectedFile().getName());
        }
    }//GEN-LAST:event_BoutonParcourirActionPerformed

    private void CheckBoxRectoVersoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxRectoVersoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxRectoVersoActionPerformed

    private void ComboBoxFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFormatActionPerformed

    private void RadioBoutonNoirBlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBoutonNoirBlancActionPerformed
        // TODO add your handling code here:
        if (RadioBoutonCouleur.isSelected()){
            RadioBoutonCouleur.setSelected(false);
        }
        RadioBoutonNoirBlanc.setSelected(true); 
    }//GEN-LAST:event_RadioBoutonNoirBlancActionPerformed

    private void ComboBoxQualiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxQualiteActionPerformed
        // TODO add your handling code here:
        String qualite=evt.getActionCommand().toString();
    }//GEN-LAST:event_ComboBoxQualiteActionPerformed

    private void BoutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonAjouterActionPerformed
        // TODO add your handling code here:
            ListModel<String> listeModel=ListImpressionPlanifiees.getModel();
            String listeModelModifiee[]=new String[listeModel.getSize()+1];
            ListModel<String> listeModelFinale;
            for (int i=0;i<listeModel.getSize();i++){
                listeModelModifiee[i]=listeModel.getElementAt(i);
            }
            listeModelModifiee[listeModelModifiee.length-1]=FileChooser.getSelectedFile().getName()
                    +"quantity"
                    +"recto"
                    +"couleur"
                    +"qualite";
            ListImpressionPlanifiees.setListData(listeModelModifiee);
            TextAreaNomFichier.removeAll();
            TextAreaNomFichier.setText("");
    }//GEN-LAST:event_BoutonAjouterActionPerformed

    private void TestFieldPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestFieldPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TestFieldPrixActionPerformed

    private void RadioBoutonCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBoutonCouleurActionPerformed
        // TODO add your handling code here:
        if (RadioBoutonNoirBlanc.isSelected()){
            RadioBoutonNoirBlanc.setSelected(false);
        }
        RadioBoutonCouleur.setSelected(true);
    }//GEN-LAST:event_RadioBoutonCouleurActionPerformed

    private void ListImpressionPlanifieesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListImpressionPlanifieesValueChanged
        // TODO add your handling code here:
        BoutonModifier.setEnabled(true);
        BoutonSupprimer.setEnabled(true);
    }//GEN-LAST:event_ListImpressionPlanifieesValueChanged

    private void SpinnerNombreCopiesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinnerNombreCopiesStateChanged
        // TODO add your handling code here:
        BoutonAjouter.setEnabled(true);
    }//GEN-LAST:event_SpinnerNombreCopiesStateChanged

    private void BoutonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSupprimerActionPerformed
        // TODO add your handling code here:
        ListModel<String> listeModel=ListImpressionPlanifiees.getModel();
        String listeModelModifiee[]=new String[listeModel.getSize()+1];
        ListModel<String> listeModelFinale;
        int j=ListImpressionPlanifiees.getSelectedIndex();
        for (int i=0;i<listeModel.getSize();i++){
            if (i!=j){
                listeModelModifiee[i]=listeModel.getElementAt(i);
            }
        }
        ListImpressionPlanifiees.setListData(listeModelModifiee);
        
        RadioBoutonNoirBlanc.setSelected(false);
        RadioBoutonCouleur.setSelected(false);
        ComboBoxFormat.setSelectedIndex(0);
        ComboBoxQualite.setSelectedIndex(0);
        SpinnerNombreCopies.setValue(0);
        CheckBoxRectoVerso.setSelected(false);
        
    }//GEN-LAST:event_BoutonSupprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAjouter;
    private javax.swing.JButton BoutonModifier;
    private javax.swing.JButton BoutonParcourir;
    private javax.swing.JButton BoutonSupprimer;
    private javax.swing.JCheckBox CheckBoxRectoVerso;
    private javax.swing.JComboBox<String> ComboBoxFormat;
    private javax.swing.JComboBox<String> ComboBoxQualite;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JLabel LabelFichier;
    private javax.swing.JLabel LabelFormat;
    private javax.swing.JLabel LabelNombreCopies;
    private javax.swing.JLabel LabelQualitéPapier;
    private javax.swing.JList<String> ListImpressionPlanifiees;
    private javax.swing.JPanel PanelFichier;
    private javax.swing.JScrollPane PanelNomFichier;
    private javax.swing.JPanel PanelOptionDroit;
    private javax.swing.JPanel PanelOptions;
    private javax.swing.JPanel PanelOptionsGauche;
    private javax.swing.JPanel PanelPlanification;
    private javax.swing.JPanel PanelPrix;
    private javax.swing.JRadioButton RadioBoutonCouleur;
    private javax.swing.JRadioButton RadioBoutonNoirBlanc;
    private javax.swing.JSpinner SpinnerNombreCopies;
    private javax.swing.JTextField TestFieldPrix;
    private javax.swing.JTextArea TextAreaNomFichier;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
